# Generated by Django 5.2.8 on 2026-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_appointment_medicineschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodreport',
            name='review_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
