# Generated by Django 5.2.8 on 2026-04-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_carejournal_volunteertask_wellwish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellwish',
            name='ngo_club_name',
            field=models.CharField(blank=True, help_text='e.g., A star football club', max_length=255, null=True),
        ),
    ]
