# Generated by Django 6.0.2 on 2026-02-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('parent', 'Parent'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
