# Generated by Django 5.2.8 on 2026-04-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
